### ISSUE TITLE
只会建议前文吗

### ISSUE THREAD

**Issue by weoutp** [mymusise/vscode-writer-assistant#1]
只会建议前文吗

**Comment by mymusise** [comment]
是的, 目前只做了文本续写, 文本改写还不支持.

**Comment by weoutp** [comment]
> 是的，目前只做了文本续写，文本改写还不支持。

我觉得是我搞错了，好像是需要下载docker，但我捣鼓了一晚上，也没高中，那条命令行怎么设置到docker里，可以详细说明下吗，谢谢……

**Comment by weoutp** [comment]
你好，我在docker hub上查到类似的插件了，但是无法点开，我用的是Mac系统，是系统不匹配吗？

**Comment by mymusise** [comment]
还没有在Mac上试, 按道理应该都支持的, 你在应用里面打开一个"终端" , 然后输入 `docker run -d -p 23423:80 --name writer-assistant-server mymusise/writer-assistant-server` 试试

**Comment by mymusise** [comment]
close it, reopen if it needs :eyes:
